### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Review by javier-godoy — DISMISSED** [review]
Mention that commit ad9c6b6 closes `#7`

**Comment by ngonzalezpazFC** [comment]
> 
> 
> Mention that commit [ad9c6b6](https://github.com/FlowingCode/ChipFieldAddon/commit/ad9c6b663f42b768a669c1ae6852fedccb3727bd) closes `#7`

Done

**Comment by javier-godoy** [comment]
@mlopezFC @ngonzalezpazFC Can you take a look at this, I'll rebase it after it's approved.

**Review by mlopezFC — COMMENTED** [review]
Just a thought: shouldn't [this commit](https://github.com/FlowingCode/ChipFieldAddon/pull/22/commits/575983ff3b134c684a5d03790141c93a2d9c4f55)'s type be "build(test)"?

**Comment by javier-godoy** [comment]
@mlopezFC 
> Just a thought: shouldn't [this commit](https://github.com/FlowingCode/ChipFieldAddon/pull/22/commits/575983ff3b134c684a5d03790141c93a2d9c4f55)'s type be "build(test)"?

`test` is not a scope.

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @mlopezFC @ngonzalezpazFC Can you take a look at this? I'll rebase it after it's approved.

LGTM

**Comment by mlopezFC** [comment]
> @mlopezFC
> 
> > Just a thought: shouldn't [this commit](https://github.com/FlowingCode/ChipFieldAddon/pull/22/commits/575983ff3b134c684a5d03790141c93a2d9c4f55)'s type be "build(test)"?
> 
> `test` is not a scope.

Yes, you're right, I might have gotten confused given that test *is* a scope in maven

**Pull request merged**
